### PR TITLE
Redux

### PR DESCRIPTION
**Pull request by milaitinen**
Data design can be found in redux-data-design below README.md - you can get the general idea of how data is stored in the redux store here. Actions, reducers, and store is found inside the redux folder.

### CODE REVIEW

**Review by aapopajunen — APPROVED** [review]
Redux <3

**Comment by AWih** [comment]
The navigation now works with redux, but the android hardware back button and possibly jest tests need to be still fixed.
See:
https://reactnavigation.org/docs/guides/redux#Handling-the-Hardware-Back-Button-in-Android
https://reactnavigation.org/docs/guides/redux#Mocking-tests

**Review by 1krt — APPROVED** [review]
Hienolta näyttää!

**Review by elisa-n — APPROVED** [review]
nättiä

**Review by AWih — APPROVED** [review]
Back button works now

**Review by liikinn — APPROVED** [review]
Back button toimii ja muutenkin näyttää hyvältä.

**Pull request merged**
